################################################################################
# GENERAL SYSTEM INFORMATION
################################################################################

# This should match the ROS Installation instructions
# see http://www.ros.org/wiki/groovy/Installation/Ubuntu#groovy.2BAC8-Installation.2BAC8-Sources.Setup_your_sources.list
ubuntu_distro: precise

# Contact information if a non-sudo user experiences a problem only an 
# administrator can solve. Useful in case the user is doing something wrong or
# there is a bug in the configuration or the update tool
# admin_contact: ADMIN NAME <admin@email>

################################################################################
# SYSTEM INSTALL CONFIGURATION
################################################################################

apt_packages:
# Packages we should not uninstall if subsequently dropped from the config
  unmanaged:
    - vim
    - subversion
    - git
    - mercurial
    - openssh-server
    - python-netifaces
    - vim-gnome
    - emacs
    - meld
    - sox

# These packages will always be sync. If any package is installed through this
# tool, then it will be removed if not present in subsequent updates
  managed:
    - ros-groovy-audio-common
    - ros-groovy-desktop-full
    - ros-groovy-rx
    - ros-groovy-rxgraph
    - ros-groovy-rxtools
    - ros-groovy-camera-umd         #uvc_camera
    - ros-groovy-qt-ros
    - ros-groovy-brown-remotelab    #teleop_twist_keyboard
    - ros-groovy-laser-drivers
    - ros-groovy-laser-filters
    - ros-groovy-openni-launch
    - ros-groovy-depthimage-to-laserscan
    - ros-groovy-pr2-simulator
    - ros-groovy-rocon-multimaster
    - ros-groovy-zeroconf-avahi-suite
    - ros-groovy-class-loader       # should get automatically pulled in, but it does not
    - ros-groovy-camera-drivers
    - ros-groovy-catkin       # should get automatically pulled in, but it does not
    - ros-groovy-serial
    - python-rosdep
    - python-rosrelease
    - python-rosinstall
    - python-wstool

################################################################################
# DEFAULT USER INSTALL CONFIG
################################################################################

default_user:
  resolve: https://raw.github.com/utexas-bwi/bwi/master/bwi-update-config/user_config.yaml
