# syntax of the user configuration
syntax_version: 0.1

# Taken from the default apt installation target
# /opt/ros/<ros_distro>
ros_distro: groovy

ws:
  rosbuild:
    type: rosbuild
    dir: ros/rosbuild_ws
    rosinstall:
      - uri: https://raw.github.com/utexas-bwi/segbot/master/rosinstall/segbot.rosinstall
      - uri: https://raw.github.com/piyushk/freenect_stack/master/rosinstall/freenect.rosinstall 
      #- uri: https://raw.github.com/utexas-bwi/multi_level_map/master/rosinstall/multi_level_map.rosinstall

  catkin:
    type: catkin
    dir: ros/catkin_ws

  gazebo:
    type: generic
    dir: ros/gazebo
    bash: |
      export GAZEBO_MODEL_PATH=~/ros/gazebo/gazebo_models:${GAZEBO_MODEL_PATH}
    rosinstall:
      - hg:
          local-name: gazebo_models
          uri: https://bitbucket.org/osrf/gazebo_models
